basePath: /
host: localhost:4000
info:
  contact:
    email: reyhan@gmail.com
    name: Reyhan
  description: Sample API Spec for Orders
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: v1.0
paths: {}
swagger: "2.0"
